"""Seed data script for knowledge point tags.
Run with: python seed_data.py
"""
import os
import sys
import json

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from app import create_app
from app.extensions import db
from app.models import Tag

TAGS = [
    # Stage 1: 语法基础
    {"name": "variables", "display_name": "变量与数据类型", "category": "basic", "stage": 1,
     "description": "C++基本变量类型（int/float/char/bool）及类型转换"},
    {"name": "io", "display_name": "输入输出", "category": "basic", "stage": 1,
     "description": "cin/cout/scanf/printf等标准输入输出操作"},
    {"name": "condition", "display_name": "条件判断", "category": "basic", "stage": 1,
     "description": "if/else/switch条件分支语句"},
    {"name": "loop", "display_name": "循环", "category": "basic", "stage": 1,
     "description": "for/while/do-while循环控制结构"},
    {"name": "array", "display_name": "数组", "category": "basic", "stage": 1,
     "description": "一维/二维数组的声明、访问和遍历"},
    {"name": "function", "display_name": "函数", "category": "basic", "stage": 1,
     "description": "函数定义、参数传递、返回值及作用域"},
    {"name": "string_basic", "display_name": "字符串处理", "category": "string", "stage": 1,
     "description": "C风格字符串和string类的基本操作"},
    {"name": "struct", "display_name": "结构体", "category": "basic", "stage": 1,
     "description": "自定义结构体类型的定义和使用"},
    {"name": "pointer", "display_name": "指针/引用", "category": "basic", "stage": 1,
     "description": "指针变量、引用传参、动态内存分配"},
    {"name": "file_io", "display_name": "文件读写", "category": "basic", "stage": 1,
     "description": "freopen/fstream文件输入输出操作"},

    # Stage 2: 基础算法
    {"name": "simulation", "display_name": "模拟", "category": "basic", "stage": 2,
     "description": "按题意直接模拟过程，考察代码实现能力"},
    {"name": "enumeration", "display_name": "枚举", "category": "basic", "stage": 2,
     "description": "穷举所有可能情况并逐一验证"},
    {"name": "sort_basic", "display_name": "排序(冒泡/选择/插入)", "category": "basic", "stage": 2,
     "prerequisite_tags": '["array", "loop"]',
     "description": "O(n²)基础排序算法的原理和实现"},
    {"name": "sort_advanced", "display_name": "排序(快排/归并)", "category": "basic", "stage": 2,
     "prerequisite_tags": '["sort_basic", "function"]',
     "description": "O(nlogn)高效排序算法及分治思想"},
    {"name": "binary_search", "display_name": "二分查找", "category": "basic", "stage": 2,
     "prerequisite_tags": '["sort_basic"]',
     "description": "有序序列上的二分查找及二分答案"},
    {"name": "prefix_sum", "display_name": "前缀和", "category": "basic", "stage": 2,
     "prerequisite_tags": '["array"]',
     "description": "一维/二维前缀和，快速求区间和"},
    {"name": "difference", "display_name": "差分", "category": "basic", "stage": 2,
     "prerequisite_tags": '["prefix_sum"]',
     "description": "差分数组，支持区间修改和单点查询"},
    {"name": "two_pointer", "display_name": "双指针", "category": "basic", "stage": 2,
     "prerequisite_tags": '["array", "sort_basic"]',
     "description": "双指针/尺取法，线性扫描解决区间问题"},
    {"name": "greedy_basic", "display_name": "贪心", "category": "basic", "stage": 2,
     "prerequisite_tags": '["sort_basic"]',
     "description": "局部最优策略推导全局最优解"},
    {"name": "high_precision", "display_name": "高精度计算", "category": "math", "stage": 2,
     "prerequisite_tags": '["array", "string_basic"]',
     "description": "大整数加减乘除运算的模拟实现"},
    {"name": "recursion", "display_name": "递推与递归", "category": "basic", "stage": 2,
     "prerequisite_tags": '["function"]',
     "description": "递推关系和递归调用的设计与实现"},
    {"name": "bit_operation", "display_name": "位运算", "category": "basic", "stage": 2,
     "prerequisite_tags": '["variables"]',
     "description": "与或非异或、移位等位运算操作及应用"},

    # Stage 3: CSP-J
    {"name": "stack", "display_name": "栈", "category": "ds", "stage": 3,
     "prerequisite_tags": '["array"]',
     "description": "后进先出(LIFO)数据结构，括号匹配/表达式求值"},
    {"name": "queue", "display_name": "队列", "category": "ds", "stage": 3,
     "prerequisite_tags": '["array"]',
     "description": "先进先出(FIFO)数据结构，层次遍历/模拟"},
    {"name": "linked_list", "display_name": "链表", "category": "ds", "stage": 3,
     "prerequisite_tags": '["pointer", "struct"]',
     "description": "单链表/双链表的插入、删除和遍历操作"},
    {"name": "dfs", "display_name": "DFS深度优先搜索", "category": "search", "stage": 3,
     "prerequisite_tags": '["recursion"]',
     "description": "递归/栈实现的深度优先搜索，全排列/迷宫"},
    {"name": "bfs", "display_name": "BFS广度优先搜索", "category": "search", "stage": 3,
     "prerequisite_tags": '["queue"]',
     "description": "队列实现的广度优先搜索，最短步数问题"},
    {"name": "dp_linear", "display_name": "线性DP", "category": "dp", "stage": 3,
     "prerequisite_tags": '["recursion", "array"]',
     "description": "一维/二维线性动态规划，LCS/LIS等经典问题"},
    {"name": "dp_knapsack_basic", "display_name": "简单背包", "category": "dp", "stage": 3,
     "prerequisite_tags": '["dp_linear"]',
     "description": "01背包、完全背包、多重背包基础"},
    {"name": "number_theory_basic", "display_name": "基础数论(GCD/LCM/素数筛)", "category": "math", "stage": 3,
     "prerequisite_tags": '["loop", "function"]',
     "description": "最大公约数、最小公倍数、埃氏筛/欧拉筛"},
    {"name": "graph_basic", "display_name": "简单图论(邻接表/矩阵/遍历)", "category": "graph", "stage": 3,
     "prerequisite_tags": '["dfs", "bfs", "array"]',
     "description": "图的存储方式及DFS/BFS遍历"},
    {"name": "string_processing", "display_name": "基础字符串处理", "category": "string", "stage": 3,
     "prerequisite_tags": '["string_basic", "array"]',
     "description": "字符串匹配、回文判断等进阶处理"},
    {"name": "hash_table", "display_name": "哈希表", "category": "ds", "stage": 3,
     "prerequisite_tags": '["array"]',
     "description": "哈希函数设计、冲突处理，O(1)查找"},
    {"name": "sliding_window", "display_name": "滑动窗口", "category": "basic", "stage": 3,
     "prerequisite_tags": '["two_pointer"]',
     "description": "定长/变长滑动窗口维护区间信息"},
    {"name": "deque", "display_name": "双端队列", "category": "ds", "stage": 3,
     "prerequisite_tags": '["queue"]',
     "description": "两端均可插入删除的数据结构"},
    {"name": "union_find", "display_name": "并查集", "category": "ds", "stage": 3,
     "prerequisite_tags": '["array"]',
     "description": "路径压缩和按秩合并，连通性判断"},
    {"name": "lis", "display_name": "最长递增子序列", "category": "dp", "stage": 3,
     "prerequisite_tags": '["dp_linear"]',
     "description": "O(nlogn)求LIS及相关变体问题"},

    # Stage 4: CSP-S
    {"name": "dp_interval", "display_name": "区间DP", "category": "dp", "stage": 4,
     "prerequisite_tags": '["dp_linear"]',
     "description": "区间合并/分割的动态规划，石子合并等"},
    {"name": "dp_tree", "display_name": "树形DP", "category": "dp", "stage": 4,
     "prerequisite_tags": '["dp_linear", "dfs", "graph_basic"]',
     "description": "在树结构上进行的动态规划"},
    {"name": "dp_bitmask", "display_name": "状压DP", "category": "dp", "stage": 4,
     "prerequisite_tags": '["dp_linear"]',
     "description": "用二进制位表示状态的动态规划"},
    {"name": "dp_digit", "display_name": "数位DP", "category": "dp", "stage": 4,
     "prerequisite_tags": '["dp_linear", "recursion"]',
     "description": "按数位分解进行的动态规划，统计满足条件的数"},
    {"name": "search_pruning", "display_name": "搜索剪枝", "category": "search", "stage": 4,
     "prerequisite_tags": '["dfs", "bfs"]',
     "description": "可行性剪枝、最优性剪枝等搜索优化技巧"},
    {"name": "search_iterative_deepening", "display_name": "迭代加深", "category": "search", "stage": 4,
     "prerequisite_tags": '["dfs"]',
     "description": "限制深度的DFS，兼顾BFS和DFS优点"},
    {"name": "search_bidirectional_bfs", "display_name": "双向BFS", "category": "search", "stage": 4,
     "prerequisite_tags": '["bfs"]',
     "description": "从起点和终点同时BFS，减少搜索空间"},
    {"name": "search_astar", "display_name": "A*搜索", "category": "search", "stage": 4,
     "prerequisite_tags": '["bfs"]',
     "description": "启发式搜索，用估价函数引导搜索方向"},
    {"name": "shortest_path", "display_name": "最短路(Dijkstra/SPFA/Floyd)", "category": "graph", "stage": 4,
     "prerequisite_tags": '["graph_basic"]',
     "description": "单源/全源最短路径算法"},
    {"name": "mst", "display_name": "最小生成树(Kruskal/Prim)", "category": "graph", "stage": 4,
     "prerequisite_tags": '["graph_basic", "union_find"]',
     "description": "无向连通图的最小生成树算法"},
    {"name": "topo_sort", "display_name": "拓扑排序", "category": "graph", "stage": 4,
     "prerequisite_tags": '["graph_basic", "queue"]',
     "description": "有向无环图的拓扑排序，依赖关系处理"},
    {"name": "lca", "display_name": "LCA最近公共祖先", "category": "graph", "stage": 4,
     "prerequisite_tags": '["graph_basic", "dfs"]',
     "description": "倍增/Tarjan求树上两点的最近公共祖先"},
    {"name": "tarjan_scc", "display_name": "强连通分量(Tarjan)", "category": "graph", "stage": 4,
     "prerequisite_tags": '["dfs", "graph_basic"]',
     "description": "Tarjan算法求有向图的强连通分量"},
    {"name": "heap", "display_name": "堆", "category": "ds", "stage": 4,
     "prerequisite_tags": '["array"]',
     "description": "二叉堆/优先队列，支持高效取最值"},
    {"name": "sparse_table", "display_name": "ST表", "category": "ds", "stage": 4,
     "prerequisite_tags": '["array", "prefix_sum"]',
     "description": "稀疏表，O(1)查询静态区间最值"},
    {"name": "bit", "display_name": "树状数组", "category": "ds", "stage": 4,
     "prerequisite_tags": '["array", "prefix_sum"]',
     "description": "支持单点修改和前缀和查询的数据结构"},
    {"name": "segment_tree", "display_name": "线段树", "category": "ds", "stage": 4,
     "prerequisite_tags": '["recursion", "array"]',
     "description": "支持区间修改和区间查询的树形数据结构"},
    {"name": "monotone_stack", "display_name": "单调栈", "category": "ds", "stage": 4,
     "prerequisite_tags": '["stack"]',
     "description": "维护单调性的栈，求最近更大/更小元素"},
    {"name": "monotone_queue", "display_name": "单调队列", "category": "ds", "stage": 4,
     "prerequisite_tags": '["queue"]',
     "description": "维护单调性的双端队列，滑动窗口最值"},
    {"name": "combinatorics", "display_name": "组合数学", "category": "math", "stage": 4,
     "prerequisite_tags": '["number_theory_basic"]',
     "description": "排列组合、二项式系数、卡特兰数等"},
    {"name": "inclusion_exclusion", "display_name": "容斥原理", "category": "math", "stage": 4,
     "prerequisite_tags": '["combinatorics"]',
     "description": "集合的并集计数，容斥公式应用"},
    {"name": "fast_power", "display_name": "快速幂", "category": "math", "stage": 4,
     "prerequisite_tags": '["recursion"]',
     "description": "O(logn)计算幂次，支持取模运算"},
    {"name": "modular_inverse", "display_name": "逆元", "category": "math", "stage": 4,
     "prerequisite_tags": '["fast_power", "number_theory_basic"]',
     "description": "模运算下的除法，费马小定理/扩展欧几里得"},
    {"name": "kmp", "display_name": "KMP字符串匹配", "category": "string", "stage": 4,
     "prerequisite_tags": '["string_processing"]',
     "description": "O(n+m)字符串匹配，next数组的构建和应用"},
    {"name": "trie", "display_name": "Trie字典树", "category": "string", "stage": 4,
     "prerequisite_tags": '["string_processing"]',
     "description": "前缀树结构，高效字符串查找和前缀匹配"},
    {"name": "string_hash", "display_name": "字符串哈希", "category": "string", "stage": 4,
     "prerequisite_tags": '["string_processing"]',
     "description": "将字符串映射为数值，O(1)子串比较"},
    {"name": "meet_in_middle", "display_name": "折半搜索", "category": "search", "stage": 4,
     "prerequisite_tags": '["enumeration", "binary_search"]',
     "description": "将搜索空间分成两半分别枚举再合并"},

    # Stage 5: 省选
    {"name": "balanced_tree", "display_name": "平衡树(Treap/Splay)", "category": "ds", "stage": 5,
     "prerequisite_tags": '["segment_tree"]',
     "description": "自平衡二叉搜索树，支持动态序列操作"},
    {"name": "persistent_ds", "display_name": "可持久化数据结构(主席树)", "category": "ds", "stage": 5,
     "prerequisite_tags": '["segment_tree"]',
     "description": "保留历史版本的数据结构，区间第k小等"},
    {"name": "heavy_light", "display_name": "树链剖分", "category": "ds", "stage": 5,
     "prerequisite_tags": '["segment_tree", "dfs", "lca"]',
     "description": "将树路径问题转化为序列问题"},
    {"name": "centroid_decomposition", "display_name": "点分治/边分治", "category": "ds", "stage": 5,
     "prerequisite_tags": '["dfs", "graph_basic"]',
     "description": "以重心为根分治处理树上路径问题"},
    {"name": "suffix_array", "display_name": "后缀数组", "category": "string", "stage": 5,
     "prerequisite_tags": '["string_hash", "sort_advanced"]',
     "description": "后缀排序及height数组，子串相关问题"},
    {"name": "suffix_automaton", "display_name": "后缀自动机", "category": "string", "stage": 5,
     "prerequisite_tags": '["string_processing"]',
     "description": "识别所有子串的最小状态自动机"},
    {"name": "ac_automaton", "display_name": "AC自动机", "category": "string", "stage": 5,
     "prerequisite_tags": '["trie", "kmp", "bfs"]',
     "description": "多模式串匹配，Trie树上构建失配指针"},
    {"name": "network_flow", "display_name": "网络流(最大流/费用流)", "category": "graph", "stage": 5,
     "prerequisite_tags": '["shortest_path", "graph_basic"]',
     "description": "最大流/最小割/费用流算法及建模"},
    {"name": "bipartite_matching", "display_name": "二分图匹配", "category": "graph", "stage": 5,
     "prerequisite_tags": '["graph_basic", "dfs"]',
     "description": "匈牙利算法/Hopcroft-Karp求最大匹配"},
    {"name": "dp_probability", "display_name": "概率DP/期望DP", "category": "dp", "stage": 5,
     "prerequisite_tags": '["dp_linear"]',
     "description": "求概率/期望的动态规划问题"},
    {"name": "game_theory", "display_name": "博弈论(SG函数)", "category": "math", "stage": 5,
     "prerequisite_tags": '["dp_linear"]',
     "description": "Nim游戏、SG函数、组合博弈理论"},
    {"name": "cdq_divide", "display_name": "CDQ分治", "category": "ds", "stage": 5,
     "prerequisite_tags": '["bit", "sort_advanced"]',
     "description": "离线分治处理偏序问题"},
    {"name": "overall_binary", "display_name": "整体二分", "category": "ds", "stage": 5,
     "prerequisite_tags": '["binary_search", "bit"]',
     "description": "对多个查询同时二分答案"},
    {"name": "matrix_power", "display_name": "矩阵快速幂", "category": "math", "stage": 5,
     "prerequisite_tags": '["fast_power", "dp_linear"]',
     "description": "矩阵乘法加速线性递推"},
    {"name": "gaussian_elimination", "display_name": "高斯消元", "category": "math", "stage": 5,
     "prerequisite_tags": '["array"]',
     "description": "求解线性方程组、行列式计算"},
    {"name": "two_sat", "display_name": "2-SAT", "category": "graph", "stage": 5,
     "prerequisite_tags": '["tarjan_scc"]',
     "description": "2-SAT问题的建图与求解"},
    {"name": "slope_optimization", "display_name": "斜率优化DP", "category": "dp", "stage": 5,
     "prerequisite_tags": '["dp_linear", "monotone_queue"]',
     "description": "利用凸包/斜率优化转移方程"},

    # Stage 6: NOI
    {"name": "fft_ntt", "display_name": "多项式(FFT/NTT)", "category": "math", "stage": 6,
     "prerequisite_tags": '["fast_power"]',
     "description": "快速傅里叶/数论变换，多项式乘法"},
    {"name": "advanced_flow", "display_name": "高级网络流", "category": "graph", "stage": 6,
     "prerequisite_tags": '["network_flow"]',
     "description": "上下界网络流、最小费用可行流等"},
    {"name": "virtual_tree", "display_name": "虚树", "category": "ds", "stage": 6,
     "prerequisite_tags": '["lca", "heavy_light"]',
     "description": "只保留关键点的压缩树结构"},
    {"name": "sam", "display_name": "SAM后缀自动机", "category": "string", "stage": 6,
     "prerequisite_tags": '["suffix_automaton"]',
     "description": "后缀自动机的高级应用"},
    {"name": "palindrome_automaton", "display_name": "回文自动机", "category": "string", "stage": 6,
     "prerequisite_tags": '["string_processing"]',
     "description": "回文树(Eertree)，统计回文子串"},
    {"name": "lct", "display_name": "Link-Cut Tree", "category": "ds", "stage": 6,
     "prerequisite_tags": '["balanced_tree"]',
     "description": "动态树结构，支持链上修改和换根"},
    {"name": "dp_plug", "display_name": "插头DP", "category": "dp", "stage": 6,
     "prerequisite_tags": '["dp_bitmask"]',
     "description": "基于轮廓线的状压DP，棋盘连通性问题"},
    {"name": "cactus_graph", "display_name": "仙人掌图", "category": "graph", "stage": 6,
     "prerequisite_tags": '["tarjan_scc"]',
     "description": "每条边最多属于一个简单环的图结构"},
    {"name": "du_sieve", "display_name": "杜教筛", "category": "math", "stage": 6,
     "prerequisite_tags": '["number_theory_basic"]',
     "description": "亚线性时间求积性函数前缀和"},
    {"name": "min25_sieve", "display_name": "Min-25筛", "category": "math", "stage": 6,
     "prerequisite_tags": '["number_theory_basic"]',
     "description": "亚线性时间求积性函数前缀和的另一种方法"},
    {"name": "computational_geometry", "display_name": "高级计算几何", "category": "math", "stage": 6,
     "description": "凸包、半平面交、旋转卡壳等几何算法"},
]


def seed_tags():
    """Seed all knowledge point tags (idempotent via upsert)."""
    app = create_app()
    with app.app_context():
        for tag_data in TAGS:
            existing = Tag.query.filter_by(name=tag_data['name']).first()
            if existing:
                # Update fields
                for key, value in tag_data.items():
                    if key != 'name':
                        setattr(existing, key, value)
            else:
                tag = Tag(
                    name=tag_data['name'],
                    display_name=tag_data['display_name'],
                    category=tag_data.get('category', 'other'),
                    stage=tag_data.get('stage', 1),
                    description=tag_data.get('description'),
                    prerequisite_tags=tag_data.get('prerequisite_tags'),
                )
                db.session.add(tag)

        db.session.commit()
        print(f"Seeded/updated {len(TAGS)} tags.")

        # Print summary
        for stage in range(1, 7):
            stage_tags = [t for t in TAGS if t.get('stage') == stage]
            stage_names = {1: '语法基础', 2: '基础算法', 3: 'CSP-J', 4: 'CSP-S', 5: '省选', 6: 'NOI'}
            print(f"  Stage {stage} ({stage_names[stage]}): {len(stage_tags)} tags")


if __name__ == '__main__':
    seed_tags()
