"""add consecutive_sync_failures to platform_account

Revision ID: 45e145c4d5d3
Revises: a8fed64020dd
Create Date: 2026-02-14 16:35:28.774821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e145c4d5d3'
down_revision = 'a8fed64020dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consecutive_sync_failures', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_account', schema=None) as batch_op:
        batch_op.drop_column('consecutive_sync_failures')

    # ### end Alembic commands ###
