"""add AI analysis error tracking

Revision ID: 79ef84cfcd4b
Revises: c3a7f1e8b924
Create Date: 2026-02-15 12:30:48.249409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ef84cfcd4b'
down_revision = 'c3a7f1e8b924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_analysis_error', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('ai_retry_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('ai_retry_count')
        batch_op.drop_column('ai_analysis_error')

    # ### end Alembic commands ###
