"""Add target_stage to student

Revision ID: 87387cefced3
Revises: 8e2dbe377167
Create Date: 2026-02-16 11:43:17.664234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87387cefced3'
down_revision = '8e2dbe377167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_stage', sa.Integer(), nullable=False, server_default='3'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('target_stage')

    # ### end Alembic commands ###
