"""add ai_skip_backfill to problem

Revision ID: 9b5cd53165d4
Revises: 84458af20925
Create Date: 2026-02-22 00:24:37.292310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5cd53165d4'
down_revision = '84458af20925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_skip_backfill', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('ai_skip_backfill')

    # ### end Alembic commands ###
