"""add last_sync_error and user_setting table

Revision ID: a8fed64020dd
Revises: 
Create Date: 2026-02-14 10:52:42.683081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8fed64020dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_setting',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('key', sa.String(length=100), nullable=False),
        sa.Column('value', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'key', name='uq_user_setting_user_key'),
    )
    with op.batch_alter_table('user_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_setting_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('platform_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_sync_error', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_account', schema=None) as batch_op:
        batch_op.drop_column('last_sync_error')

    with op.batch_alter_table('user_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_setting_user_id'))

    op.drop_table('user_setting')
    # ### end Alembic commands ###
